/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [],
    theme: {
        extend: {},
    },
    daisyui: {
        darkTheme: "main",
        themes: [
            {
                main: {
                    primary: "#84cc16",
                    secondary: "#1e3a8a",
                    accent: "#fde68a",
                    neutral: "#1f2937",
                    "base-100": "#111827",
                    info: "#38bdf8",
                    success: "#4ade80",
                    warning: "#fbbf24",
                    error: "#f87171",
                },
            },
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
        ],
    },
    plugins: [require("daisyui")],
};
